appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: kfYS9ABVizIAVdh/sQJrFg78j8CbbmPCfjEPRzsUn8rCxKXmSRIBzWdnd9GDgRNy/3EQCLXBKs4RgISI2xY0Dezx8WLfmdNiVvYKZveeJTstIE0euBf1teBaqWhsFsAmyHPQ1xKL1b/Dux0X3sC0B1v4r+WI6w/5JhOrnIHNHnZyQIJ0q+sduv6Y3ns0rEezKoGFQ/SNLsYGfEXpuxBIfgcv6yKzVU9DRCgyL86jCxD9CnT1P4gkv5KrL2yTvQpe9PuOkwnyZy0m0EZmzg2tNNOQtd7HO2TTfjdNcpwUcQLCeF64zijnecp9HoIE73QeAATTPjQfhRdU4azx1m4bu1EO31ZM4JS9J4gACzjKIMueZgpI/UnQCLOYkemBXnDRDIed7Hn9XHoT2vZD7M64Ul2GHDGAIQP2ZuxyDZN6XbcBlMaxXW+k+4Qx1nrwjxyO3Ot87PQF2yhHOwAoOsUjOtey3SwHnBcywhB/2BwpDGHP/g2hJ57dmHgon/cBan5KzOToRtqnm3h/n7MmX4+plDnmb/ktE7VsUI0So1JOdSLXQpoSHk9QOQKCKVYA5/ESpjQ21TOCG44OHjCF2vs67Bkf4i1AN3+f+FsViHTbepSIclJwoyxeygg1uo6VBqP5Pa+TZqx4wGw9WgySCbfN10X9iP1oQFZnrCF2BgCSlpk=}
